// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ABzev-hklM2Dq4J9bv8bNVLN4ng3Ltw',
    appId: '1:655679523222:web:640e5c191d27c90b83b5b7',
    messagingSenderId: '655679523222',
    projectId: 'nutritrack-66125',
    authDomain: 'nutritrack-66125.firebaseapp.com',
    storageBucket: 'nutritrack-66125.firebasestorage.app',
    measurementId: 'G-BF6YDLKNHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5xXbG0o6JRU-Rc4D2TnHTiWMdRowqVs',
    appId: '1:655679523222:android:8023a9bbf63c81ca83b5b7',
    messagingSenderId: '655679523222',
    projectId: 'nutritrack-66125',
    storageBucket: 'nutritrack-66125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsurwM15LwftZuVYeOozl0X8O38IzCpQ',
    appId: '1:655679523222:ios:3c2e69c5a052363083b5b7',
    messagingSenderId: '655679523222',
    projectId: 'nutritrack-66125',
    storageBucket: 'nutritrack-66125.firebasestorage.app',
    iosClientId: '655679523222-qu8ohov6bgdr49iouo2l8m56mf64d71f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCsurwM15LwftZuVYeOozl0X8O38IzCpQ',
    appId: '1:655679523222:ios:3c2e69c5a052363083b5b7',
    messagingSenderId: '655679523222',
    projectId: 'nutritrack-66125',
    storageBucket: 'nutritrack-66125.firebasestorage.app',
    iosClientId: '655679523222-qu8ohov6bgdr49iouo2l8m56mf64d71f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ABzev-hklM2Dq4J9bv8bNVLN4ng3Ltw',
    appId: '1:655679523222:web:9ab7fcbea02dbada83b5b7',
    messagingSenderId: '655679523222',
    projectId: 'nutritrack-66125',
    authDomain: 'nutritrack-66125.firebaseapp.com',
    storageBucket: 'nutritrack-66125.firebasestorage.app',
    measurementId: 'G-29B2MYQGHN',
  );

}