name: myapp
description: "Valar - Child Growth & Vaccination Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # Google Sign In
  google_sign_in: ^6.2.1

  # Charts
  fl_chart: ^0.68.0

  # URL Launcher (for doctors nearby screen)
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/valar_bg.jpeg